### ISSUE TITLE
JSON Web Token Registry pre-assignment wording change needed

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-msg-wrap#101] opened 2024-06-25 19:42 UTC
IANA experts feedback: I believe that Section 3.1 needs to be revised to say that the json-record is the value of the “cwm” JWT claim and the cbor-record is the value of the “cwm” CWT claim.

**Comment by thomas-fossati** [comment] 2024-06-25 20:58
I believe the requested prose is already in the [second paragraph of Section 3.1](https://www.ietf.org/archive/id/draft-ietf-rats-msg-wrap-05.html#section-3.1-2):

> _"A CMW record carried in a cmw JWT claim ([Section 8.2](https://www.ietf.org/archive/id/draft-ietf-rats-msg-wrap-05.html#iana-jwt)) MUST be a json-record. A CMW record carried in a cmw CWT claim ([Section 8.1](https://www.ietf.org/archive/id/draft-ietf-rats-msg-wrap-05.html#iana-cwt)) MUST be a cbor-record."_

**Comment by nedmsmith** [comment] 2024-06-25 21:00
Is it a problem if we also say this in section 3.1?

**Comment by thomas-fossati** [comment] 2024-06-25 21:05
> Is it a problem if we also say this in section 3.1?

The quoted sentences are taken from section 3.1.

**Comment by thomas-fossati** [comment] 2024-06-26 21:09
This is a duplicate of #94 which has been addressed by #95 and published in -05.

**Closed by thomas-fossati** 2024-06-26 21:09 UTC
